# See http://localhost:8080/configuration-as-code/reference for full list of options
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "USER:Overall/Administer:admin"
        - "GROUP:Overall/Read:authenticated"
security:
  scriptApproval:
    approvedSignatures:

  queueItemAuthenticator:
    authenticators:
      - global:
          strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://localhost:8080/
jobs:
  # Initial Jenkins seed job - will be overwritten with the job of the same name in
  # the Github repo once run. If this job is not present in the repo and removeAction
  # is 'DELETE', then the job will abort automatically as it will try to delete itself.
  - script: |
      job('jenkins_seed_jobs') {
          triggers {
              cron('* * * * *')
          }
          scm {
              git {
                  remote {
                      github('lsmarsden/jenkins-jobs')
                  }
              }
          }
          steps {
              dsl {
                  external('jobs/*.groovy')
      
                  removeAction('DELETE')
              }
          }
      }
